#---- MODEL PARAMETERS
MODEL_PARAM: # input in the same order as class initialization
  BATCH_SIZE: 512
  TIME_FRAMES: 5
  KEYPOINTS: 17
  CHANNEL_IN: 3
  HEADS: 3
  LAYERS: 6
  LAST_MLP: 512
  CLASSES: 8

#---- MODEL CONFIG
DS_PATH: '/home/etorres/Documents/in-work/datasets/activity-recognition/local-dataset/'
TB_PATH: '/home/etorres/Documents/in-work/training/activity-recognition/runs/ae-ensemble-lds-01'
TB_COMMENT: '_our_ds'
MODEL_OUT_PATH: '/home/etorres/Documents/in-work/models/activity-recognition-models/autoencoder/model_4a/model.pth'

#---- TRAINING PARAMETERS
TRAIN_PARAM:
  LEARNING_RATE: .001
  WEIGHT_DECAY: .0001
  EPOCHS: 100
